version: "3.3"

services:
  web:
    build:
      context: "."
    volumes:
     - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
     - "8080:80"
    environment:
      - DD_PROD=1.2.3.4
      - DD_PROD_PORT=80
      - DD_PROD_WEIGHT=5
      - DD_CANDIDATE=5.6.7.8
      - DD_CANDIDATE_PORT=80
      - DD_CANDIDATE_WEIGHT=1
